# Absolute path to the directory containing the Defects4J repository
# The structure should look like this:
# D
# - Defects4J
# -- Lang
# --Math
# ---18
# MUST BE IDENTIFIED
repo=D:\\Defects4J

# Name of the debugging topic
# MUST BE IDENTIFIED
name=Math

# The id of the bug to be debugged
# MUST BE IDENTIFIED
id=18

# JDB commands that are expected to use
commands=run,stop,step,print,locals,fields,classes,methods,thread,threadgroup,cont,clear,where

# Running ChatDBG on what task
# 1. defects4j
# 2. maven(not supported yet)
task=defects4j

# The port that the debugger listens on
port=5005

# The interval between sending the command and trying to read the response
interval=500

# The size of buffer reading from the debugger
bufferSize=4000